#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Open a cloudflare tunnel
##?
##? Usage:
##?   cloudflare-tunnel <tunnel-token>
docs::parse "$@"

cloudflared tunnel run --token $1