#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Update all submodules to the latest commit on their remote branch
##?
##? Usage:
##?   update-submodules
docs::parse "$@"

git submodule update --recursive --remote