#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Update dotly to the latest commit on its remote branch
##?
##? Usage:
##?   update-submodules
docs::parse "$@"

git submodule update --init --remote modules/dotly